#ifndef __GAME_DEFINES_H
#define __GAME_DEFINES_H

/*
 *  GameDefines.h
 *  CoreEngine3D
 *
 *  Created by Jody McAdams on 10/10/10.
 *  Copyright 2010 GameJelly Online. All rights reserved.
 *
 */

#define IPHONE4_ASPECTRATIO 0.667f

//Frame rate
#define FPS 60.0f	
#define ONE_OVER_FPS (1.0f/FPS)

#define GAME_IPHONE_SCALE_FOR_IPAD_IS_HALF 1

#define RENDERLOOP_ENABLED 1

#define EVERY_BLOCK_HAS_FISH 0
#define PARTICLE_TEST_PRINT 0
#define PARTICLE_TEST_STRESS 0
#define PRINT_ERRORS 0
#define DEBUG_BLOCK_DRIP 0
#define ALL_BLOCKS_SAME_COLOR 0

#define INFINITE_SUPER_MOVES 0
#define QUICKLY_GET_SUPERMOVES 0

#define LIGHT_TEST_MODE 0
#define USE_HIGH_QUALITY_COLORS 0
#define BACKGROUND_AND_BORDER_ONLY_MODE 0
#define ENABLE_MULTISAMPLING (1 && m_supportsMultisampling)
#define MULTISAMPLING_NUMSAMPLES 4
#define USE_RETINA_DISPLAY 1
#define DISPLAY_FPS 0
#define TRAIL_TEST 0
#define ENABLE_OUTLINE_RENDERING 0
#define DRAW_PHYSICS 0
#define UPDATE_PHYSICS 1
#define SHOW_MENU_BUTTONS 0
#define DRAWPARTICLES 1
#define DEBUG_DRAWPARTICLESASLINESTRIP 0

#define SILLYPERFORMANCEBOOST_ON 0
#define TEST_SIMPLE_SHADERS 0
#define TEST_ENABLE_MIKE_STUFF 1
#define TEST_DRAWBG 1
#define GRAPHICS_STRESS_TEST 0
#define TEST_ENABLESCREENCLEAR 1
#define TEST_SHOW_TOUCHXY_DURINGREPLAY 0
#define TEST_FISH_BAR_CYCLE 0
#define TEST_FISH_BAR_FORCE_MAX 0
#define TEST_SHOW_PAUSE_BUTTON 1
#define TEST_FORCE_INSTANT_LOSE 0
#define TEST_SHOW_CLIENT_AND_HOST 0
#define TEST_SPAM_ATTACKBLOCKS_LIKE_WHOA 0
#define SUBMISSION_ENABLE_GAMECENTER 1
#define MAX_SILENT_TIME 5.0
#endif
